[build-system]
requires = ["setuptools > 40.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jupyter-jsonnet"
description = "A simple Jsonnet kernel for Jupyter"
dependencies = ["ipykernel", "jsonnet"]
version = "0.1"
